<?php
namespace Database\Seeders;

use App\Models\Horse;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class HorseSeeder extends Seeder
{
    public function run(): void
    {
        $horses = $this->horses();

        foreach ($horses as $data) {
            $data['slug'] = Str::slug($data['name']);
            Horse::updateOrCreate(['slug' => $data['slug']], $data);
        }
    }

    private function horses(): array
    {
        return [
            // ── Episode 1 ────────────────────────────────────────────────────
            [
                'name'           => 'Job 1917',
                'episode'        => 1,
                'description'    => 'The very first horse CaseOh ever bet on. Chat voted for him at 5:1 odds over "For Sale," and he delivered — winning CaseOh his first ever $50 payout and setting the entire series in motion.',
                'notes'          => 'Won CaseOh\'s first bet. Blue trophy holder. Later became a parent of the legendary Generation H alongside Salad Days.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'For Sale',
                'episode'        => 1,
                'description'    => 'The first horse CaseOh laid eyes on in the very first race of the series. He thought it "looked the fastest," but chat overruled him and voted for Job 1917 instead.',
                'notes'          => 'CaseOh\'s gut said this was the one. Chat said otherwise.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Muesli',
                'episode'        => 1,
                'description'    => 'A colossal 4-year-old standing 16 hands tall and weighing in at a staggering 1,600 lbs — double the weight of most competitors. A majestic unit who was never going to win a race but inspired endless commentary.',
                'notes'          => '"Musli is like double the weight of anybody else in the race, dog." Likely involved in a hay-eating competition.',
                'parents'        => null,
                'weight_lbs'     => 1600,
                'age_at_capture' => 4,
            ],
            [
                'name'           => 'Mass Ejection',
                'episode'        => 1,
                'description'    => 'CaseOh\'s first personal horse pick — a 1-year-old at only 770 lbs. The name was a statement of confidence. The race was not. Threatened repeatedly with the glue factory.',
                'notes'          => '"You\'re going to get turned into glue, Mass Ejection. You hear me?"',
                'parents'        => null,
                'weight_lbs'     => 770,
                'age_at_capture' => 1,
            ],
            [
                'name'           => 'Salad Days',
                'episode'        => 1,
                'description'    => 'A 1,100 lb powerhouse known for popping wheelies mid-race and still winning. CaseOh called him "the best horse I\'ve ever seen in my life." Later sired the legendary Generation H with Job 1917.',
                'notes'          => '"He popping a wheelie." Parent of Generation H. Parent of Princess Glitter (with Cubert).',
                'parents'        => null,
                'weight_lbs'     => 1100,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Big Dipper',
                'episode'        => 1,
                'description'    => 'The eternal underdog. Listed at 10:1 odds, the worst in the race. CaseOh bet $5 on him and told him "Nobody believes in you, but I do." Big Dipper repaid that faith by finishing second-to-last.',
                'notes'          => 'CaseOh\'s sentimental pick. 10:1 odds. "Big Dipper was the worst horse in this race and didn\'t get last."',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => "Chris Redfield's Pink Thong Juice",
                'episode'        => 1,
                'description'    => 'CaseOh\'s very first captured horse, named by chat in honor of the Resident Evil protagonist. A 2-year-old weighing 1,177 lbs. Lost his debut race and was released back into the wild. Later produced an offspring.',
                'notes'          => '"We\'re sending Chris Redfield\'s pink thong juice to the line, baby." Lost. Released. Had a kid anyway.',
                'parents'        => null,
                'weight_lbs'     => 1177,
                'age_at_capture' => 2,
            ],
            [
                'name'           => 'Leon Kennedy Chair Sniffer',
                'episode'        => 1,
                'description'    => 'Descendant of Chris Redfield\'s Pink Thong Juice. CaseOh\'s first genuinely winning horse — went 3-for-3 in races and earned over $1,500. "Leon Kennedy\'s chair sniffer is three for three, but I\'m not proud of that one."',
                'notes'          => 'Three wins. $1,500 earned. Parent of Binky (and eventually grandparent of Scoot\'s lineage).',
                'parents'        => ["Chris Redfield's Pink Thong Juice"],
                'weight_lbs'     => 1161,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Ank',
                'episode'        => 1,
                'description'    => 'Found at 7 years old, ancient by horse standards. CaseOh took him in out of sheer compassion and raced him one final time against what turned out to be a literal cheetah. He almost won. He then retired with full dignity to the horse retirement home.',
                'notes'          => '"I\'m sorry I got you in your glory years and took you out here, Ank." Retired. Never to race again.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => 7,
            ],
            [
                'name'           => 'Scoot',
                'episode'        => 1,
                'description'    => 'Offspring of a rabbit. Won a race. CaseOh discovered he could sell Scoot for $2,000 because of his rabbit lineage and race win. "Scoot, you\'re so mid and your genetics suck." Yet somehow became parent of the GOAT, Tater.',
                'notes'          => 'One win. Parent of Tater (with Unknown). His mediocrity produced greatness.',
                'parents'        => ['rabbit', 'Unknown'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Binky',
                'episode'        => 1,
                'description'    => 'Offspring of Leon Kennedy Chair Sniffer. Had enormous shoes to fill. Failed. Finished behind a horse called "Not a Number" in what CaseOh described as "the fastest finish I\'ve ever seen." Released to the wild.',
                'notes'          => '"It isn\'t all genetics." Released. "Maybe you can at least pass on the genetics."',
                'parents'        => ['Leon Kennedy Chair Sniffer'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Tater',
                'episode'        => 1,
                'description'    => 'THE GOAT. Also known as Potato, Spud, and "the horse of all time." Offspring of Scoot and an unknown parent. Won two regular races and then the $250-entry-fee championship for a $2,500 prize. Earned CaseOh a legendary silver lasso. Retired to the horse retirement home at age 8. "I will remember Tater for as long as I live."',
                'notes'          => 'GOAT. Three total race wins including championship. Parent of Cheesy Tot, AFA, and (via DNA) Potato, Satellite, Bobcat and others. "Your genetics, your speed, has carried us to a net worth of $25,000."',
                'parents'        => ['Scoot', 'Unknown'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],

            // ── Episode 2 ────────────────────────────────────────────────────
            [
                'name'           => 'Kickstand',
                'episode'        => 2,
                'description'    => 'A wild horse with an unusual long tail that CaseOh theorized would function as a "kickstand" to prevent wheelie-flipping. Captured specifically for breeding potential. Bred with Tater to produce the Anti-Flip Apparatus.',
                'notes'          => '"It\'s going to act like a kickstand." Bred with Tater. Parent of AFA.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Anti-Flip Apparatus',
                'episode'        => 2,
                'description'    => 'Offspring of Kickstand and Tater. Specifically engineered to have the speed genetics of Tater combined with the tail-length stability of Kickstand, creating a horse that theoretically cannot flip backwards. CaseOh was extremely confident in this concept.',
                'notes'          => '"Look at the anti-flip apparatus. Look at it, dog." Carries Tater\'s genetics.',
                'parents'        => ['Kickstand', 'Tater'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'The Big Cheese',
                'episode'        => 2,
                'description'    => 'Purchased from a "shady farm" for $320. The first horse in the series to possess the coveted speed-enhancing boots. His parent is Maximum Carnage. The boots were passed down to his offspring, creating a generational boot dynasty.',
                'notes'          => '"Big Cheese was the first horse to have the boots." Parent is Maximum Carnage. Sold after passing on the boots.',
                'parents'        => ['Maximum Carnage'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'These Boots Were Made for Walking',
                'episode'        => 2,
                'description'    => 'Offspring of Kickstand and Cheesy Tot. Inherited the legendary boots from The Big Cheese\'s lineage. Won multiple races. Nearly unbeatable with the boots equipped. "These boots were made for walking and that\'s just what they\'ll do on the line."',
                'notes'          => 'Boot wearer. Multiple wins. Parents: Kickstand + Cheesy Tot. The boots are generational.',
                'parents'        => ['Kickstand', 'Cheesy Tot'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Generation H',
                'episode'        => 2,
                'description'    => 'Offspring of Job 1917 and Salad Days — two horses from the very first race of the series. Described as "the fastest horse I\'ve ever seen. Even faster than Tater." Suspected of jumping the gun repeatedly. Still racing competitively at 7-8 years old. "Its parents are Salad Days and Job 1917. This is the fastest horse in existence."',
                'notes'          => 'Blue trophy winner. Repeated false start accusations. The benchmark for early-game speed. Refused for sale by its owner. Won the champion race at $250 entry fee.',
                'parents'        => ['Job 1917', 'Salad Days'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Big Stea',
                'episode'        => 2,
                'description'    => 'A 3-year-old weighing 1,700 lbs — the heaviest horse ever recorded in the series. Shockingly fast, but later revealed to be entirely boot-dependent. "Big Stea was boot made." Won races that left jaws on the floor, then was mediocre without the boots.',
                'notes'          => '1,700 lbs at 3 years old. Boot-dependent speed. "We took the boots off Big Stea and he was mid."',
                'parents'        => null,
                'weight_lbs'     => 1700,
                'age_at_capture' => 3,
            ],
            [
                'name'           => 'Pineapple Express',
                'episode'        => 2,
                'description'    => 'A legitimate champion horse with a race win under its belt, purchased and used to breed Step Express alongside Generation H. The name lived up to the speed.',
                'notes'          => 'Champion horse. Parent of Step Express (with Generation H).',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Step Express',
                'episode'        => 2,
                'description'    => 'Offspring of Pineapple Express and Generation H. Beat Generation H in a nail-biting champion race — the first horse to definitively outrace the previously unbeatable Generation H. "Can you believe Step Express just beat Generation H? I actually cannot believe that."',
                'notes'          => 'First horse to beat Generation H in a champion race. Parents: Pineapple Express + Generation H.',
                'parents'        => ['Pineapple Express', 'Generation H'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],

            // ── Episode 3 ────────────────────────────────────────────────────
            [
                'name'           => 'Potato',
                'episode'        => 3,
                'description'    => 'A direct DNA clone of Tater, produced via the DNA extraction lab. "We just cloned Tater." Looked identical to Tater and performed at the same level. Dominated in early race tests before Satellite emerged as a challenger.',
                'notes'          => 'DNA clone of Tater. "This is going to be a guaranteed win. I don\'t care who we\'re going against."',
                'parents'        => ['Tater (DNA clone)'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Satellite',
                'episode'        => 3,
                'description'    => 'A DNA lab experiment incorporating fish DNA and "some other crazy stuff." Went head-to-head with Tater\'s clone in an epic multi-race showdown. Accused of taking false starts in nearly every race. "Tater is just a regular horse, man. Meanwhile Satellite is mixed between like a fish." CaseOh concluded Antenna at its peak was faster than Tater — and Satellite was Antenna\'s offshoot.',
                'notes'          => 'Fish DNA + other experiments. Accused cheater (false starts). Final tally: 5 wins vs Tater\'s 4 in their rivalry.',
                'parents'        => ['DNA experiment'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Antenna',
                'episode'        => 3,
                'description'    => 'A DNA experiment that was, at peak, faster than Tater — but catastrophically unstable. Would flip over mid-race in virtually every attempt. Retired to the legends wing of the retirement home having never officially won a single race. Parent of Block Chevy and Corn Nugget with Tater.',
                'notes'          => '"Antenna at its peak is faster than Tater." Never officially won. Retired. Parent of Block Chevy (with Tater).',
                'parents'        => ['DNA experiment'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Block Chevy',
                'episode'        => 3,
                'description'    => 'Offspring of Tater and Antenna — the two fastest horses in history combined into one. Instantly dominant. "Nobody else is even on the screen." Twin of Corn Nugget. One of the most hyped births in the series.',
                'notes'          => '"Nobody else is even on the screen." Twin of Corn Nugget. Parents: Tater + Antenna. Immediately dominant.',
                'parents'        => ['Tater', 'Antenna'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Marshmallow',
                'episode'        => 3,
                'description'    => 'A DNA creation bred from Corn Dog and the fish air tank. Fast with boots — impressively so — but would flip forward (not backward) without them. A tragically flawed genius. "Marshmallow just ain\'t built good enough, man."',
                'notes'          => 'Boots = fast. No boots = flips forward. Parents: Corn Dog + fish/air-tank creation.',
                'parents'        => ['Corn Dog', 'fish air tank'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => "Bob's Best Pal",
                'episode'        => 3,
                'description'    => 'Discovered in the wild, seemingly unremarkable. Turned out to be faster than Tater — a paradigm-shattering discovery. "The first time I thought nothing could be faster." Became the new baseline. Parent of Evil Bob and Bobcat.',
                'notes'          => '"When I first discovered Bob, I actually didn\'t think anything could be faster than Bob." Wild-found. Beat Tater.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Evil Bob',
                'episode'        => 3,
                'description'    => 'A DNA extraction of Bob\'s Best Pal. "Weighs exactly one pound more than Bob\'s best pal." Marginally faster than the original. "He really is evil." Parent lineage fed into the creation of Bobcat.',
                'notes'          => 'One pound heavier than Bob. Slightly faster. "Science has gone too far."',
                'parents'        => ["Bob's Best Pal (DNA extract)"],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Bobcat',
                'episode'        => 3,
                'description'    => 'The apex predator — a DNA mix of Tater and Bob\'s Best Pal. "Just looks like a horse with cat ears." Fastest thing created to that point. CaseOh was so confident in Bobcat that he declared he would "get naked on Twitch" if Bobcat ever lost a straight race without flipping.',
                'notes'          => '"It legitimately does not matter who we\'re up against." DNA mix of Tater + Bob. "Horse with cat ears."',
                'parents'        => ['Tater (DNA)', "Bob's Best Pal (DNA)"],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Goober',
                'episode'        => 3,
                'description'    => 'A DNA extraction result. Faster than Bobcat at peak, but inconsistently so. "I think at his peak Goober\'s faster, but Goober just isn\'t consistent enough." Created via the DNA extraction machine. A volatile talent.',
                'notes'          => 'Faster than Bobcat when consistent, but isn\'t. DNA experiment.',
                'parents'        => ['DNA experiment'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Ostrich',
                'episode'        => 3,
                'description'    => 'A wild experimental creation that defied categorization. When it doesn\'t flip over, nothing in the game can beat it. "If Ostrich doesn\'t flip, there is not a single horse in any of these races that can win." Unfortunately, it flips. A lot.',
                'notes'          => 'Unstoppable when upright. Flips constantly. "Ostrich would be slow as Christmas at this point" — said after newer horses emerged.',
                'parents'        => ['DNA experiment'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],

            // ── Episode 4 ────────────────────────────────────────────────────
            [
                'name'           => 'Lemon Pepper',
                'episode'        => 4,
                'description'    => 'The reigning "crown champion" and official speed benchmark heading into the final episode. Consistently fast. "Lemon pepper is officially the baseline speed for us now." Beat 5G, Barcode, and Billy in the final four-horse championship. Best recorded time: 5.5.',
                'notes'          => 'Crown champion. Official speed baseline. Best time: 5.5. Won the final showdown.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => '5G',
                'episode'        => 4,
                'description'    => 'A completely natty (no DNA modification) horse bred naturally. Recorded the best single-run time of 5.4 in the series. Won multiple rounds of the final four-horse showdown. "5G is the fastest thing we have right now. It\'s 5G. No joke."',
                'notes'          => 'Natty. Best time: 5.4. Won several rounds in the final four-horse test. Eventual lineage founder for the next episode.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Barcode',
                'episode'        => 4,
                'description'    => 'A DNA experiment praised above all others for its consistency. "Barcode legitimately is built for it — with a beer gut." While not always the outright fastest, Barcode\'s repeatability made CaseOh argue it was arguably the best horse overall.',
                'notes'          => '"Barcode being so consistent literally makes barcode the best horse." Beer gut. DNA experiment. Extremely consistent.',
                'parents'        => ['DNA experiment'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'QR Code',
                'episode'        => 4,
                'description'    => 'A DNA experiment and the weakest of the final four horses. "QR code sucks. QR code\'s terrible." Considered for exclusion from the gene pool entirely. "I\'m not even afraid to give QR code to nature."',
                'notes'          => '"QR code sucks." The runt of the final four. DNA experiment.',
                'parents'        => ['DNA experiment'],
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
            [
                'name'           => 'Billy',
                'episode'        => 4,
                'description'    => 'A natty horse — no DNA modification, just pure natural breeding. Had a photo-finish with 5G that the stream debated for several minutes. "Isn\'t it absolutely insane that the two fastest ones are the natties?" Billy took it in the rematch.',
                'notes'          => 'Natty. Photo finish with 5G. "The two fastest ones are the natties." Won the rematch against 5G.',
                'parents'        => null,
                'weight_lbs'     => null,
                'age_at_capture' => null,
            ],
        ];
    }
}